version: '2.27.3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring-boot-app-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      PROD_REDIS_PASSWORD: ${PROD_REDIS_PASSWORD}
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  spring-boot-app:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - spring-boot-app-network
    depends_on:
      - redis
    environment:
      PROD_REDIS_HOST: ${PROD_REDIS_HOST}
      PROD_REDIS_PORT: ${PROD_REDIS_PORT}
      PROD_REDIS_PASSWORD: ${PROD_REDIS_PASSWORD}

networks:
  spring-boot-app-network:
    driver: bridge
