spring:
#  profiles:
#    active: "dev"
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  coolSMS:
    apikey: ${DEV_SMS_API_KEY}
    apiSecret: ${DEV_SMS_API_SECRET}
    senderNumber: ${SMS_SENDER_NUMBER}

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#          google:
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#          kakao:
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao