spring:
  application:
    name: BoardBuddy
#  profiles:
#    active: common
#  config:
#    activate:
#      on-profile: "common"
  config:
    location: file:/config/

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
