#server:
#  port: 8080
spring:
  profiles:
    active: "prod"

#  config:
#    location: file:/config/

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
  cloud:
    aws:
      s3:
        bucket-name: ${PROD_S3_BUCKET_NAME}
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${PROD_AWS_ACCESS_KEY}
        secret-key: ${PROD_AWS_SECRET_KEY}
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://ec2-52-79-123-145.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/naver
          google:
            redirect-uri: http://ec2-52-79-123-145.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/google
          kakao:
            redirect-uri: http://ec2-52-79-123-145.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/kakao