#server:
#  port: 8080

spring:
  config:
    location: file:/config/

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      repositories:
        enabled: false
      password: ${PROD_REDIS_PASSWORD}

  cloud:
    aws:
      credentials:
        access-key: ${PROD_AWS_ACCESS_KEY}
        secret-key: ${PROD_AWS_SECRET_KEY}

  cool-sms:
    api-key: ${PROD_SMS_API_KEY}
    api-secret: ${PROD_SMS_API_SECRET}
    sender-number: ${PROD_SMS_SENDER_NUMBER}