#name: Deploy Spring Boot APP to Amazon Linux 2023
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest   # Runner는 빌드 스크립트 전송만 담당
#
#    env:
#      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
#      PROD_REDIS_HOST: ${{ secrets.PROD_REDIS_HOST }}
#      PROD_REDIS_PORT: ${{ secrets.PROD_REDIS_PORT }}
#      PROD_REDIS_PASSWORD: ${{ secrets.PROD_REDIS_PASSWORD }}
#      PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
#      PROD_DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
#      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
#      PROD_AWS_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_KEY }}
#      PROD_AWS_SECRET_KEY: ${{ secrets.PROD_AWS_SECRET_KEY }}
#      PROD_SMS_API_KEY: ${{ secrets.PROD_SMS_API_KEY }}
#      PROD_SMS_API_SECRET: ${{ secrets.PROD_SMS_API_SECRET }}
#      PROD_SMS_SENDER_NUMBER: ${{ secrets.PROD_SMS_SENDER_NUMBER }}
#      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
#      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#      NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }} >> env.list
#      NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }} >> env.list
#      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }} >> env.list
#      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }} >> env.list
#      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }} >> env.list
#      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }} >> env.list
#      PROD_S3_BUCKET_NAME: ${{ secrets.PROD_S3_BUCKET_NAME }} >> env.list
#
#    steps:
#      # 리포지토리를 체크아웃
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      # Spring Boot 애플리케이션을 위한 JDK 21을 설정
#      - name: Set up JDK 21
#        uses: actions/setup-java@v2
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      # Gradle을 사용하여 Spring Boot 애플리케이션을 빌드
#      - name: Build Spring Boot app with Gradle
#        run: ./gradlew build -Dspring.profiles.active=common,prod
#
#      # Spring Boot 애플리케이션을 위한 Docker 이미지를 빌드
#      - name: Build Docker image for Spring Boot app
#        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest -f Dockerfile .
#
#      # Docker에 로그인
#      - name: Docker Login
#        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#
#      # Docker 이미지를 푸시
#      - name: Push Docker image for Spring Boot app
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest
#
#      # SSH 키를 설정
#      - name: Add SSH Key
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      # 환경 변수 파일을 생성
#      - name: Create environment variables file
#        run: |
#          echo SPRING_DATASOURCE_URL=${{ secrets.PROD_DB_URL }} > env.list
#          echo SPRING_DATASOURCE_USERNAME=${{ secrets.PROD_DB_USERNAME }} >> env.list
#          echo SPRING_DATASOURCE_PASSWORD=${{ secrets.PROD_DB_PASSWORD }} >> env.list
#          echo SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.PROD_AWS_ACCESS_KEY }} >> env.list
#          echo SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY=${{ secrets.PROD_AWS_SECRET_KEY }} >> env.list
#          echo SPRING_DATA_REDIS_HOST=${{ secrets.PROD_REDIS_HOST }} >> env.list
#          echo SPRING_DATA_REDIS_PORT=${{ secrets.PROD_REDIS_PORT }} >> env.list
#          echo SPRING_DATA_REDIS_PASSWORD=${{ secrets.PROD_REDIS_PASSWORD }} >> env.list
#          echo SPRING_COOL_SMS_API_KEY=${{ secrets.PROD_SMS_API_KEY }} >> env.list
#          echo SPRING_COOL_SMS_API_SECRET=${{ secrets.PROD_SMS_API_SECRET }} >> env.list
#          echo SPRING_COOL_SMS_SENDER_NUMBER=${{ secrets.PROD_SMS_SENDER_NUMBER }} >> env.list
#          echo SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} >> env.list
#          echo SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} >> env.list
#          echo SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> env.list
#          echo SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> env.list
#          echo SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} >> env.list
#          echo SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} >> env.list
#          echo SPRING_CLOUD_AWS_S3_BUCKET_NAME=${{ secrets.PROD_S3_BUCKET_NAME }} >> env.list
#          echo SPRING_PROFILES_ACTIVE=common,prod >> env.list
#
#      # Redis 설정 파일 생성
#      - name: Create redis configuration file
#        run: |
#          echo "bind 0.0.0.0" > redis.conf
#          echo "protected-mode no" >> redis.conf
#          echo "port 6379" >> redis.conf
#          echo "requirepass ${{ secrets.PROD_REDIS_PASSWORD }}" >> redis.conf
#
#      # 파일을 EC2로 전송
#      - name: Transfer files to EC2
#        run: |
#          scp -o StrictHostKeyChecking=no src/main/resources/application-common.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/application-common.yml
#          scp -o StrictHostKeyChecking=no src/main/resources/application-prod.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/application-prod.yml
#          scp -o StrictHostKeyChecking=no env.list ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/env.list
#          scp -o StrictHostKeyChecking=no docker-compose.prod.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/docker-compose.yml
#          scp -o StrictHostKeyChecking=no redis.conf ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/redis.conf
#          scp -o StrictHostKeyChecking=no nginx.conf ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/nginx.conf
#
#      # EC2에 배포
#      - name: Deploy to EC2
#        run: |
#          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
#          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
#          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest
#
#          # Docker 네트워크를 생성
#          sudo docker network create spring-boot-app-network || true
#
#          # Redis 컨테이너를 실행
#          if [ $(sudo docker ps -a -q -f name=redis) ]; then
#              sudo docker stop redis
#              sudo docker rm redis
#          fi
#          sudo docker run -d --name redis \
#            -v /home/ubuntu/redis.conf:/usr/local/etc/redis/redis.conf \
#            --network spring-boot-app-network \
#            -e PROD_REDIS_PASSWORD=${PROD_REDIS_PASSWORD} \
#            -p 6379:6379 redis:latest redis-server /usr/local/etc/redis/redis.conf
#
#          # Spring Boot 애플리케이션 컨테이너를 실행
#          if [ $(sudo docker ps -a -q -f name=spring-boot-app) ]; then
#              sudo docker stop spring-boot-app
#              sudo docker rm spring-boot-app
#          fi
#          sudo docker run -d --name spring-boot-app \
#            --env-file /home/ubuntu/env.list \
#            -v /home/ubuntu/application-common.yml:/config/application-common.yml \
#            -v /home/ubuntu/application-prod.yml:/config/application-prod.yml \
#            --network spring-boot-app-network \
#            -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest \
#            --spring.config.location=/config/application-common.yml,/config/application-prod.yml
#
#          # Nginx 설정 파일 복사 및 Nginx 재시작
#          sudo cp /home/ubuntu/nginx.conf /etc/nginx/sites-available/default
#          sudo nginx -t
#          sudo systemctl restart nginx
#
#          # Certbot 설치 및 인증서 갱신
#          sudo apt update
#          sudo apt install certbot python3-certbot-nginx -y
#          sudo certbot renew --nginx
#
#          # 컨테이너 상태 확인
#          sudo docker ps -a
#          # Spring Boot 애플리케이션 로그 확인
#          sudo docker logs spring-boot-app
#          EOF


name: Build & Deploy Spring Boot to EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1) 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) JDK 21 설치 및 설정 (Gradle 빌드용)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3) Spring Boot 애플리케이션 빌드 (fat JAR 생성)
      - name: Build JAR
        run: ./gradlew clean bootJar -Dspring.profiles.active=common,prod

      # 4) Docker 이미지 빌드 (커밋 SHA 태그 사용)
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:${{ github.sha }} -f Dockerfile .

      # 5) Docker Hub 로그인
      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} \
            | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # 6) 이미지 푸시 및 latest 태그로 추가 푸시
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:${{ github.sha }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1) 저장소 코드 및 설정 파일 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) SSH 에이전트 시작 (프라이빗 키 로드)
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) env.list 파일 생성 (프로덕션 환경변수 일괄 설정)
      - name: Create env.list
        run: |
          cat > env.list <<EOF
          SPRING_DATASOURCE_URL=${{ secrets.PROD_DB_URL }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.PROD_DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
          SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.PROD_AWS_ACCESS_KEY }}
          SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY=${{ secrets.PROD_AWS_SECRET_KEY }}
          SPRING_DATA_REDIS_HOST=${{ secrets.PROD_REDIS_HOST }}
          SPRING_DATA_REDIS_PORT=${{ secrets.PROD_REDIS_PORT }}
          SPRING_DATA_REDIS_PASSWORD=${{ secrets.PROD_REDIS_PASSWORD }}
          SPRING_COOL_SMS_API_KEY=${{ secrets.PROD_SMS_API_KEY }}
          SPRING_COOL_SMS_API_SECRET=${{ secrets.PROD_SMS_API_SECRET }}
          SPRING_COOL_SMS_SENDER_NUMBER=${{ secrets.PROD_SMS_SENDER_NUMBER }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
          SPRING_CLOUD_AWS_S3_BUCKET_NAME=${{ secrets.PROD_S3_BUCKET_NAME }}
          SPRING_PROFILES_ACTIVE=common,prod
          EOF

      # 4) redis.conf 파일 생성 (Redis 컨테이너 설정)
      - name: Create redis.conf
        run: |
          cat > redis.conf <<EOF
          bind 0.0.0.0
          protected-mode no
          port 6379
          requirepass ${{ secrets.PROD_REDIS_PASSWORD }}
          EOF

      # 5) env.list, Redis, Spring 설정, Nginx 설정을 한 번에 EC2로 전송
      - name: Transfer config files to EC2
        run: |
          scp -o StrictHostKeyChecking=no \
            env.list \
            redis.conf \
            src/main/resources/application-common.yml \
            src/main/resources/application-prod.yml \
            nginx.conf \
            ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/

      # 6) EC2에 SSH 접속 → Docker 배포 → Nginx 설정 덮어쓰기 → 재시작
      - name: Pull & Run on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -eux
          
            # ─── Docker 설치/시작 (없으면) ───
            if ! command -v docker >/dev/null 2>&1; then
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable --now docker
            fi
          
            # ─── 애플리케이션 컨테이너 최신화 ───
            echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} \
              | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest
            sudo docker network create spring-boot-app-network || true
            sudo docker rm -f spring-boot-app || true
            sudo docker run -d --name spring-boot-app \
              --env-file /home/ec2-user/env.list \
              -v /home/ec2-user/application-common.yml:/config/application-common.yml \
              -v /home/ec2-user/application-prod.yml:/config/application-prod.yml \
              --network spring-boot-app-network \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/boardbuddy:backend-latest \
              --spring.config.location=/config/application-common.yml,/config/application-prod.yml
          
            # ─── Nginx 설치 & 서비스 준비 ───
            if ! rpm -q nginx >/dev/null 2>&1; then
              sudo dnf install -y nginx
            fi
            sudo systemctl enable nginx
          
            # ─── 로그·PID 디렉터리 생성 ───
            sudo mkdir -p /run/nginx /var/log/nginx /var/cache/nginx
            sudo chown -R nginx:nginx /var/log/nginx /var/cache/nginx
          
            # ─── 설정 파일 덮어쓰기 ───
            sudo mv /home/ec2-user/nginx.conf /etc/nginx/nginx.conf
          
            # ─── 문법 검사 & 재시작 ───
            sudo nginx -t
            sudo systemctl restart nginx
          
            # ─── Certbot 설치 및 인증서 갱신 ───
            sudo dnf install -y certbot python3-certbot-nginx
            sudo certbot renew --nginx --non-interactive --quiet
          
          EOF

